version: "3.8"

services:
  web:
    build: .
    container_name: todo_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/todo_db
      - JWT_SECRET_KEY=your_jwt_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: todo_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
